### ISSUE TITLE
Issue when using Vuforia based Unity Project

### ISSUE THREAD

**Issue by X2Stone** [DavidPeicho/davidpeicho.github.io#17]
Hi,

Thank you so much for your awesome work on integrating Unity into a SwiftUI project ! I was looking for that since months !
I tested it and it works like a charm !

So I tried to make it work with my own Unity Project (project that uses "Vuforia", an awesome AR plugin, better than ARFoundation for image tracking), and it compiles but it crash when running on my device... I get :

dyld: Library not loaded: @rpath/Vuforia.framework/Vuforia
  Referenced from: /private/var/containers/Bundle/Application/BA3B3A3D-0FA7-4100-B486-0522C6D324FD/sandbox.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
(lldb)

I don't know if it's related to your work or not... I tried to find on the internet what could be the cause of that issue but didn't find the answer (or old posts of 2017...)

**Comment by DavidPeicho** [comment]
It looks like your issue is based on the fact the library isn't found. The line:

> dyld: Library not loaded: @rpath/Vuforia.framework/Vuforia

Means that the dynamic library can't be found and so can't be dynamically linked. When building your Unity project, do you have a way to specifiy what library you want to link and where to find them? This may be an extra step after the XCode project generation. You are suppose to find a file called `Vuforia.framework` which is the dynamic library you are looking.

I wouldn't think the issue is a problem with the repository.

**Comment by X2Stone** [comment]
Thanks a lot for your answer !
Solved the problem by adding the Vuforia.framework directly to the Sandbox project instead of leaving it in the Unity-iPhone project.

**Comment by SoferChee** [comment]
I also have the same problem, may I ask how you operated specifically

**Comment by SoferChee** [comment]
> Thanks a lot for your answer ! Solved the problem by adding the Vuforia.framework directly to the Sandbox project instead of leaving it in the Unity-iPhone project.

I also have the same problem, may I ask how you operated specifically

**Comment by share49** [comment]
Anyone knows how to solve this issue? Thank you very much!!
